install:
	mkdir -p /usr/local/yamss/lib
	cp -a db2jcc.jar /usr/local/yamss/lib

buildinstall:
	mkdir -p /tmp/gemssbuildroot/usr/local/yamss/lib
	cp -a db2jcc.jar /tmp/gemssbuildroot/usr/local/yamss/lib
